hello:
  message: "Sheila"

one:
  two:
    three: 3
    four: 4

---

spring:
  config:
        activate:
            on-profile: prod

hello:
  done: "mumbai"
  message: "Shashi"

one:
  two:
    three: 4
    four: 5


---

spring:
  config:
    activate:
      on-profile: dev

hello:
  message: "Bhushan"
  done: "not yet"

one:
  two:
    three: 4
    four: 5

